### ISSUE TITLE
Cross-Compile WiringPi

### ISSUE THREAD

**Issue by embeddedshiv** [WiringPi/WiringPi#105]
How to Cross-Compile the WiringPi library for the Raspberry Pi over Ubuntu 10.8

**Comment by 2bndy5** [comment]
I've had some trouble doing this... In a github action workflow that uses ubuntu-latest (which I think recently switched to ubuntu 20.04), compiling WiringPi with env vars, `CC` & `CXX`, set to arm-gnueabihf-g** compilers errors out with the linker reporting that libcrypt can't be found. Also to compile executables with WiringPi, I needed to link the executables to `-lcrypt -lrt`; this info is not declared in the WiringPi's `./build` output. 

Hope this helps at least a little.
