### ISSUE TITLE
question: regarding pins usable for clock 

### ISSUE THREAD

**Issue by wothke** [WiringPi/WiringPi#109]
The below comment in wiringPi.c suggests that only pins 4 and 21 are usable as a clock output:

// gpioToGpClkALT:
//	ALT value to put a GPIO pin into GP Clock mode.
//	On the Pi we can really only use BCM_GPIO_4 and BCM_GPIO_21
//	for clocks 0 and 1 respectively, however I'll include the full
//	list for completeness - maybe one day...

What is meant by this and is it still true for RaspberryPi4B? I have just used GPIO20 with ALT5/CPCLK0 on my RaspberryPi4 and it actually seems to output my configured clock frequency. Is there some kind of problem that I might be overlooking?

**Comment by liffiton** [comment]
I'm afraid I don't have an answer myself, but I just enabled Discussions, and I'm going to move this over to the Q&A category there.
