### ISSUE TITLE
Lcd.c driver incorrect start address for 4x16 displays

### ISSUE THREAD

**Issue by ggsubs** [WiringPi/WiringPi#125]
When a 4 row, 16 col LCD is used with the lcd.c driver the 3rd and 4th line content is shifted by 4 positions to the right.
The issue is the Row offsets are assumed to be the same for all display layouts. In case of the 4 line 16 pos displays the start address needs to change from:
`static const int rowOff [4] = { 0x00, 0x40, 0x14, 0x54 } ;`
to 
`static const int rowOff [4] = { 0x00, 0x40, 0x10, 0x50 } ;`
as described in https://www.avrfreaks.net/sites/default/files/forum_attachments/OPTREX_DMC_HD44780compatible_manual.pdf on page 20

Some displays deviate from this even further and custom row offset init would be desirable.

**Comment by liffiton** [comment]
Hm.  So if I'm understanding everything correctly, it looks like it has the correct values for a 4x20 character display, and that may be all the positioning function was tested on.

From the datasheet, I'm thinking a proper fix could use `lcd->cols` to determine the correct offset for the 3rd and 4th rows.  As a barely-here maintainer, I'm afraid I don't have time to do that nor any way to test it.  Most work on this repo is done via pull requests now, though, and I'd welcome one of those.

Thanks for the report!
