### ISSUE TITLE
Software PWM increase frequency

### ISSUE THREAD

**Issue by muttistefano** [WiringPi/WiringPi#126]
Hello everyone,
has anyone tried to increase the software PWM frequency by changing the sleeping time inside the Thread?
I figured the "100" inside the sleeping call are supposed to be PULSE_TIME defined prior.
I am actually interested in seeing how the computational demand changes.
If no one has ever tried that i will give it a try and post the results.
Thanks

**Comment by youngkin** [comment]
I'd be interested in benchmark results.

I have the same understanding regarding PULSE_TIME. IIRC it's not used anywhere, but was probably intended to be used in place of the magic number '100'.

**Comment by muttistefano** [comment]
Hi,
i actually try to lower it starting from 100 until 2, and i noticed a slight CPU increase on the RPI4, using ubuntu 20 64bit.
The motor i am controlling sounds much better now.
i cannot check the PWM shape cause i dont have an oscilloscope in theese days but i might post some results as soon as i get one.
I dont know how long is the "switching life" of a digital pin so i hope i didn't short it too much by increasing the frequency

**Comment by liffiton** [comment]
Thanks for investigating and reporting.

In the code, it looks like the comment about a <100 pulse width hammering the CPU only applies if either of the HIGH or LOW times of one PWM cycle is less than 100 microseconds.  And then it's only in a hard loop for any specific period that is less than 100usec.  For example if you have a 90usec HIGH and a 410usec LOW, it's only in a hard loop 18% of the time.  And RPi boards are all multicore for a long time now, so you'll only hog one core anyway.  Higher frequencies are probably fine in most cases.

If I'm reading the code correctly, the PWM cycle length is X microseconds, where X = that "magic number" times the `range` parameter set in `softPwmCreate()`.  So if you set the magic number to 2 and have a range of 100, for example, the PWM cycle length is 200usec.  In that case, your worst-case is a PWM value of 99 or 101, which would use the CPU-hogging loop delay for 99 out of every 200usec.  It would consume about 50% of one core.  With a range of 200, your frequency would be cut in half, and your worst-case CPU usage would be as well.  That's if I'm understanding the code correctly, at least.

I'm not aware of any switching life for pins.  After all, much smaller transistors in CPUs as well as transistors used to switch high-frequency signals like ethernet or HDMI are switching at far higher frequencies for far longer.  You're probably just fine!

**Comment by liffiton** [comment]
[I've enabled Discussions for this repo, and I'll move this thread over there now.]
