### ISSUE TITLE
WiringPi package for RPi OS Bullseye

### ISSUE THREAD

**Issue by seamusdemora** [WiringPi/WiringPi#131]
Is there a WiringPi package available for the new Bullseye release? By that, I mean an `apt` installation. Apologies as I've not actually tried this as I'm waiting for an answer ***before*** I install Bullseye.

If not, does this project have plans for addressing this - or know if any of the other forks are?

**Comment by Kepsz** [comment]
Saddly, there is none. But you can install it from the source folder, just download it with git.
