### ISSUE TITLE
Warning message in building WiringPi on Raspberry 4

### ISSUE THREAD

**Issue by jifbrodeur** [WiringPi/WiringPi#133]
When issuing a build I get the following warning:
drcNet.c: In function \u2018authenticate\u2019:
drcNet.c:112:24: warning: \u2018%s\u2019 directive writing up to 1023 bytes into a region of size 1021 [-Wformat-overflow=]
drcNet.c:89:14:
       return &buf [10] ;
              ~~~~~~~~~  
drcNet.c:112:24:
   sprintf (salted, "$6$%s$", challenge) ;
                        ^~
drcNet.c:112:3: note: \u2018sprintf\u2019 output between 5 and 1028 bytes into a destination of size 1024
   sprintf (salted, "$6$%s$", challenge) ;

**Comment by liffiton** [comment]
It looks like this is a spurious warning.  The function that returns `challenge` can return a string 1013 bytes long at most, but the compiler isn't clever enough to determine that.

Nevertheless, I'll push a small tweak to quiet the compiler there.
