### ISSUE TITLE
how to add wiringPi on buildroot as package (how to write .mk file)

### ISSUE THREAD

**Issue by hmz-rhl** [WiringPi/WiringPi#166]
I need to include wiring pi on buildroot package but i have to write an .mk file to explain to buildorrt how to crosscompile this package

**Comment by kevintom98** [comment]
WiringPi can be enabled in menuconfig. It is under Legacy config options

**Comment by a91943** [comment]
Can't you force the compilation process? Or it's any other way of adding WiringPI to my custom linux image?
