### ISSUE TITLE
'gpio' utility and library functions report when it is being used on unsupported hardware

### ISSUE THREAD

**Issue by mstroh76** [WiringPi/WiringPi#200]
Currently, it is possible to install and run the 'gpio' utility and use the library functions on unsupported systems.

With this issues, only arm and aarch will be supported / early exit on unsupported platforms.

**Comment by seamusdemora** [comment]
FWIW, I think this is a great idea. Also solves the problem of supporting the older-model RPis; put this message in for the older models tht aren't currently supported - **until** that older model is supported.  win-win

**Comment by mwallner** [comment]
what 'older-model RPis' are you referring to @seamusdemora ?

**Comment by mstroh76** [comment]
this change is for unusual kernels and operation systems, unsupported architecture and unknown hardware.
ubuntu provides wiringpi for x86_64  - what a crazy idea 

simply try `apt install wiringpi` on mint or ubuntu laptop :rofl:
