### ISSUE TITLE
WiringPi ISR does not work with current Kernel (6.6+)

### ISSUE THREAD

**Issue by mwallner** [WiringPi/WiringPi#204]
By dropping GPIO sysfs WiringPi ISR does not work anymore.

**users currently relying on WiringPi should _NOT_ upgrade to the latest kernel at the moment, please stand by for another week or so**

This is a known bug and the maintainer team is working on quickfix that'll re-enable basic ISR support as well as a long-term solution that'll ensure all hardware revisions are supported in a meaningful manner.

More information may be found in discussions:
* https://github.com/WiringPi/WiringPi/discussions/201
* https://github.com/WiringPi/WiringPi/discussions/202

**Comment by mstroh76** [comment]
Tested:

- Pi4 [armhf] :ok:
- Pi5 [aarch64] :ok:
- Pi1Rev1 [armhf] :ok:
- Pi1Rev1 [armhf] Bullseye - Kernel 5.15.61+ :ok:
