### ISSUE TITLE
what exactly need to be changed to use /dev/gpiochip methode?

### ISSUE THREAD

**Issue by LaneaLucy** [WiringPi/WiringPi#237]
i need to port some software and i would like to make it compatible with old and new kernels, so what would be neede to make the software compatible with new /dev/gpiochip kernel interface but also with old interfaces?

thx in advance

**Comment by mstroh76** [comment]
WiringPi numbering: replace wiringPiSetup() ->   wiringPiSetupGpioDevice(WPI_PIN_WPI)
BCM numbering:  replace wiringPiSetupGpio() ->   wiringPiSetupGpioDevice(WPI_PIN_BCM)

wiringPiSetupGpioDevice /  /dev/gpiochip works with all kernels buster, bullseye, bookworm
