### ISSUE TITLE
Version 3.6 doesn't work for RPI-CM4S

### ISSUE THREAD

**Issue by sheldon-blackshire** [WiringPi/WiringPi#262]
I discovered WiringPi doesn't work properly for the compute module 4s. On further digging, I found the function _piBoardId()_  in _WiringPi\wiringPi\wiringPi.c_ didn't have a case **PI_MODEL_CM4S**  when switching by the RaspberryPiModel.  The library worked as intended after adding the case and rebuilding.

**Comment by mstroh76** [comment]
Thank you, we needed someone to confirm.

**Comment by sheldon-blackshire** [comment]
Awesome, thanks! I'll let you know if I find any more problems on the CM4S.
