### ISSUE TITLE
build warning - Raspberry Pi 4 Bookworm : "chmod - root.root"

### ISSUE THREAD

**Issue by Yeshu-777** [WiringPi/WiringPi#279]
When building on Raspberry Pi 4 Bookworm 64 Bit..

chown: warning: '.' should be ':' : root.root

A quick edit of : /WiringPi/gpio/Makefile & change root.root to root:root resolves the chmod problem and all compiles without warnings.

Yeshu777

**Comment by mstroh76** [comment]
must be an old version, it has already been resolved

**Comment by mstroh76** [comment]
still some cases found
