### ISSUE TITLE
unregister ISR

### ISSUE THREAD

**Issue by DEvil0000** [WiringPi/WiringPi#28]
wiringPiISR() will register a ISR. works well.

but then your program finishes execution. the program is not running anymore (ps -ef). you start a different program what is not using ISR at all.
it looks like the other program is kind of pausing execution at some point and waiting for a interrupt to occur. when you send signals on the pin used by the ISR the second program resumes.

if i set the ISR pin mode to output at the end of program one i will get process two running normal afterwards.

pinMode(Pin, OUTPUT);

edit:
i think there should be something like:
wiringPiISR(Pin, INT_EDGE_NONE)

**Comment by lukaszjakubek** [comment]
Also noticed that GPIO pins are not unexported after program exits. I thing some cleanup function, which cancel interrupt treads and reset pins, will be appreciated.

**Comment by sun-alf** [comment]
Please redirect your notices to paroga/WiringPi [forked from WiringPi/WiringPi]. "WiringPi/WiringPi" depot is not supported.
