### ISSUE TITLE
WiringPi error/warning : sudo gpio load i2c

### ISSUE THREAD

**Issue by shiftleftplusone** [WiringPi/WiringPi#40]
I'm getting an error for WiringPi by sudo gpio load i2c:

pi@raspberrypi:~ $ sudo gpio load i2c
gpio: Warning (not an error): File not present: /dev/i2c-0

I have a Raspi 2B,
gpio -v shows no errors though.

pi@raspberrypi:~ $ gpio -v
gpio version: 2.26
Copyright (c) 2012-2015 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
Type: Model 2, Revision: 1.1, Memory: 1024MB, Maker: Sony

what's wrong or faulty?

**Comment by sun-alf** [comment]
Please refer to rep "paroga/WiringPi"
