### ISSUE TITLE
QT cross compile

### ISSUE THREAD

**Issue by giridhar123** [WiringPi/WiringPi#84]
Good morning. I've an ubuntu enviroment to do cross-compiling from ubuntu (with QT) to raspberry PI 4.
I've downloaded and compiled your library (from the raspberry with no errors) and executed again the rsync commands (from ubuntu) but when I try to compile QTCreator says:
`cannot find -lwiringPi
collect2: error: ld returned 1 exit status`
Thanks in advice.

**Comment by giridhar123** [comment]
Problem solved deleting all files from ubuntu and re-sync again with the Rasp and re-compiling QT.

**Comment by liffiton** [comment]
Glad you got it to work!
