### ISSUE TITLE
GPCLK0 clock generation on raspberry pi 4B

### ISSUE THREAD

**Issue by LIII-XXII** [WiringPi/WiringPi#96]
Hello,

I am using is WiringPi 2.50 from the `apt` repositories (latest Raspbian).
If I understand the pin numbering correctly, this should let me generate a 1MHz clock on GPIO4 / GPCLK0:
```
gpio mode 7 clock
gpio clock 7 1000000
```
However, I see GPIO4 stay at 3.3v on my scope.

Has this changed for the Pi 4 maybe?
```
# cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.2
```

Does one need to enable / disable something in config.txt for that clock to be usable maybe?
Here is my `/boot/config.txt`:
```
# grep /boot/config.txt -ve"^#"
disable_overscan=1
dtparam=audio=on

[pi4]
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
```

**Comment by liffiton** [comment]
The situation is a bit complicated, I'm afraid.  2.50 doesn't support the 4b.  This repository has newer code that does support the 4b, but it is not packaged in Raspbian.  There is a discussion about what to do with it in Raspbian going forward here: RPi-Distro/repo#214.
